version: "3.8"
services:
    shortener:
        container_name: shortener-api
        restart: unless-stopped
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
            - "9229:9229"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        networks:
            - app-sorturl

    redis:
        image: redis
        container_name: redis_shortener
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - app-sorturl

volumes:
    node_modules:

networks: 
    app-sorturl:
        name:
            sortener_app_mynetwork