version: "3.5"
services:
    # app:
        # container_name: sort-url-api
        # build: # "context" and "dockerfile" fields have to be under "build"
        #     context: .
        #     dockerfile: ./Dockerfile # Use for Development
        #     # dockerfile: ./Dockerfile #Use for Production
        # ports:
        #     - "3000:3000" #Server
        #     # - "40404:9001" #Supervisor
        # volumes:
        #     - .:/app
        # env_file:
        #     - ./.env
        # networks:
        #     - app-sorturl
    # sqllite:
    #     image: a9688bd1d9bb
    #           # platform: linux/x86_64 # Only for Macs (m1,m2)
    #     ports:
    #         - "4406:8080"
    #     # volumes:
    #     #     - ./src/db/dev.db:/var/lib/sqld
    #     # environment:
    #         # MYSQL_ROOT_PASSWORD: "root"
    #               #TZ: America/Bogota
    #     networks:
    #         - app-network 
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
networks: 
    app-sorturl:
        name:
            bmk_mynetwork
